[firebase]
apiKey            = "AIzaSyAuOB16aTViilVi8EdABpgr5UbLTjbMlGQ"
authDomain        = "smart-dustbin-c601d.firebaseapp.com"
databaseURL       = "https://smart-dustbin-c601d-default-rtdb.firebaseio.com"
projectId         = "smart-dustbin-c601d"
storageBucket     = "smart-dustbin-c601d.firebasestorage.app"
messagingSenderId = "496456603709"
appId             = "1:496456603709:web:1202817519e53631193254"
measurementId     = "G-N8GJX4RPNR"
